export const WORKS = [
  {
    id: "01",
    title: "smart-storage",
    role: "Open Source Author",
    year: "2023",
    tag: "npm Package",
    word: "ZAP!",
    tone: "green",
    stat: "NPM",
    statLabel: "Package",
    stack: "TypeScript · Web Storage API · SSR",
    blurb:
      "A robust, SSR-safe, production-ready wrapper around Web Storage (localStorage / sessionStorage / in-memory) for modern JavaScript apps. Framework-agnostic and fully typed.",
    win: "Published on npm. Used in production across multiple projects. Zero dependencies.",
  },
  {
    id: "02",
    title: "DIA — AI Chat-bot",
    role: "Lead Frontend",
    year: "2024",
    tag: "AI · Realtime",
    word: "BLIP!",
    tone: "ink",
    stat: "<100ms",
    statLabel: "Response Time",
    stack: "React · TypeScript · WebSockets",
    blurb:
      "Led the design and implementation of DIA, a real-time AI assistant frontend system. Architected as a framework-agnostic npm package for wide reusability across products.",
    win: "Delivered as a standalone reusable package. Real-time streaming interface with sub-100ms response feedback.",
  },
  {
    id: "03",
    title: "Snappfood.biz",
    role: "Front-End Developer",
    year: "2022",
    tag: "Platform · SnappKitchen",
    word: "SNAP!",
    tone: "red",
    stat: "+34%",
    statLabel: "Sales Growth",
    stack: "React · Redux · Webpack · SCSS · BEM",
    blurb:
      "Full refactor of the snappfood.biz web app — the vendor-facing platform for SnappKitchen (a Snapp Group subsidiary) serving 6M+ users. Rebuilt with React, Redux, and Webpack optimizations for scale.",
    win: "+34% growth in organizational sales. Admin panel scaled with BEM and component architecture for long-term consistency.",
  },
  {
    id: "04",
    title: "Badge System",
    role: "Front-End Engineer",
    year: "2024",
    tag: "E-Commerce · Digikala",
    word: "POW!",
    tone: "blue",
    stat: "+31%",
    statLabel: "PDP Conversion",
    stack: "React · TypeScript · TailwindCSS",
    blurb:
      "A front-end badge system built to communicate urgency and scarcity across Digikala's product detail pages — one of the biggest e-commerce platforms in the Middle East with 9.7M items and 100k daily orders.",
    win: "+31% PDP conversion rate to add-to-cart. Rolled out across the full 9.7M product catalogue.",
  },
  {
    id: "05",
    title: "PLP Generator",
    role: "Front-End Engineer",
    year: "2024",
    tag: "SEO · Digikala",
    word: "ZOOM!",
    tone: "yellow",
    stat: "+20%",
    statLabel: "Organic Traffic",
    stack: "Next.js · React Query · TypeScript",
    blurb:
      "A dynamic product listing page generator with FACET navigation, built for SEO performance on a platform serving 100k daily orders. Leveraged Next.js SSR and React Query for fast, crawlable category pages.",
    win: "+20% organic traffic. Improved crawlability and indexing across thousands of category pages.",
  },
  {
    id: "06",
    title: "AlgoDaric",
    role: "Front-End Developer",
    year: "2020",
    tag: "FinTech · Extensions",
    word: "WHIRR!",
    tone: "blue",
    stat: "+17%",
    statLabel: "Profitability",
    stack: "JavaScript · Chrome Extension API · Node.js",
    blurb:
      "A suite of browser extensions and an algorithmic trading bot built on financial algorithms (MACD on RSI divergence detection) — designed to increase trading accuracy and automate long-term strategies.",
    win: "+17% trading profitability via divergence detection. Browser extension user accuracy improved by 13.6%.",
  },
];

export const PANEL_LAYOUT = ["p1", "p2", "p3", "p4", "p5", "p6"];

export const SKILLS = [
  "TypeScript!",
  "React!",
  "Next.js!",
  "TailwindCSS!",
  "TanStack Query!",
  "Zustand!",
  "Redux!",
  "SCSS!",
  "Jest / TDD!",
  "NX Monorepo!",
  "Core Web Vitals!",
  "CI/CD!",
];
